version: "3.9"

services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:80" 
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - socialhub-network
    depends_on:
      - auth-service

  # The service name was changed from user-service to auth-service
  auth-service:
    build: ./services/auth-service
    ports: 
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - redis
    networks:
      - socialhub-network
  post-service:
    build: ./services/post-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/post-service/.env
    depends_on:
      - redis
    networks:
      - socialhub-network

  redis:
    image: redis:alpine
    networks:
      - socialhub-network

  kafka:
    image: apache/kafka-native
    networks:
      - socialhub-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
networks:
  socialhub-network:
    name: socialhub-network