version: "3.9"

services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:80" 
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - socialhub-network
    depends_on:
      - auth-service

  # The service name was changed from user-service to auth-service
  auth-service:
    build: ./services/auth-service
    ports: 
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - redis
    networks:
      - socialhub-network

  redis:
    image: redis:alpine
    networks:
      - socialhub-network

networks:
  socialhub-network:
    name: socialhub-network