version: "3.9"

services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - socialhub-network
    depends_on:
      - auth-service

  # The service name was changed from user-service to auth-service
  auth-service:
    build: ./services/auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - redis
    networks:
      - socialhub-network
  post-service:
    build: ./services/post-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/post-service/.env
    depends_on:
      - redis
      - kafka
    networks:
      - socialhub-network

  redis:
    image: redis:alpine
    networks:
      - socialhub-network

  kafka:
    image: apache/kafka:3.7.1
    networks:
      - socialhub-network
    ports:
      - "9092:9092"
    restart: always
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs


networks:
  socialhub-network:
    name: socialhub-network
    driver: bridge
