services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - socialhub-network
    depends_on:
      - auth-service
      - post-service
      - notification-service
      - users-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - redis
    networks:
      - socialhub-network

  post-service:
    build: ./services/post-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/post-service/.env
    depends_on:
      - redis
      - kafka
    networks:
      - socialhub-network

  notification-service:
    build: ./services/notification-service
    ports:
      - "5002:5002"
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - kafka
    networks:
      - socialhub-network

  users-service:
    # --- CHANGE 1: Corrected 'service' to 'services' ---
    build: ./services/users-service
    ports:
      - "5003:5003"
    # --- CHANGE 2: Corrected env_file to point to the actual file ---
    env_file:
      - ./services/users-service/.env 
    depends_on: 
      - kafka
    networks:
      - socialhub-network
      
  redis:
    image: redis:alpine
    networks:
      - socialhub-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  kafka:
    image: apache/kafka:3.7.1
    networks:
      - socialhub-network
    ports:
      - "9092:9092"
    restart: always
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs

networks:
  socialhub-network:
    name: socialhub-network
    driver: bridge
