services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - socialhub-network
    depends_on:
      - auth-service

  # The service name was changed from user-service to auth-service
  auth-service:
    build: ./services/auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - redis
    networks:
      - socialhub-network
  post-service:
    build: ./services/post-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/post-service/.env
    depends_on:
      - redis
      - kafka
    networks:
      - socialhub-network

  redis:
    image: redis:alpine
    networks:
      - socialhub-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - socialhub-network
    restart: always

networks:
  socialhub-network:
    name: socialhub-network
    driver: bridge
